X11 v1.1.0 release candidate

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -37,10 +37,131 @@ dnl Checks for header files.
 AC_STDC_HEADERS
 AC_HAVE_HEADERS(unistd.h io.h pthread.h)
 
-dnl Checks for library functions.
+x11="true"
+
+AC_ARG_ENABLE(x11,
+		[  --enable-x11   Build the FreeAmp X11 GUI],
+		[case "${enableval}" in
+		  yes) x11="true" ;;
+		  no) x11="false" ;;
+		  *) AC_MSG_ERROR(bad value ${enableval} for --enable-x11) ;;
+		esac])
+
+dnl ******************
+dnl Checks for X stuff
+dnl ******************
+
+if test "$x11"="true"; then
+  AC_PATH_X
+  AC_PATH_XTRA
+
+  if test "x$no_x" = "xyes"; then 
+    AC_MSG_ERROR([
+*** X libraries or include files not found. Check 'config.log' for 
+*** more details.])
+  fi
+
+  CFLAGS="$CFLAGS $X_CFLAGS"
+  LDFLAGS="$LDFLAGS $X_LDFLAGS $X_LIBS"
+
+  AC_CHECK_LIB(X11, XOpenDisplay, x11="true",
+    x11="false"
+    echo X11 not found. X11 UI build disabled.
+  )
+
+  if test "$x11" = "true"; then
+     AC_CHECK_LIB(Xext, XShapeQueryExtension, x11="true",
+       x11="false"
+       echo X11 Shape Extension not found.  X11 UI build disabled.
+     )
+
+  fi
+
+  dnl ******************
+  dnl Check for libc5.  If found warn the user about potential problems
+  dnl ******************
+
+  AC_MSG_CHECKING(for libc5)
+  AC_TRY_RUN([
+#include <stdio.h>
+#include <ctype.h>
+asm (".weak gnu_get_libc_version");
+asm (".weak __libc_version");
+asm (".weak __linux_C_lib_version");
+
+extern const char * gnu_get_libc_version (void);
+extern const char * __linux_C_lib_version;
+extern const char __libc_version [];
+
+int main() {
+  int libcmajor = 0, libcminor = 0, libcteeny = 0;
+  if (((&__linux_C_lib_version != 0)
+       && ((&__libc_version != 0) || (gnu_get_libc_version != 0)))
+      || (!(&__linux_C_lib_version != 0) && !(&__libc_version != 0)
+         && !(gnu_get_libc_version != 0)))
+  {
+    libcmajor = 0;
+    libcminor = 0;
+    libcteeny = 0;
+  }
+  else
+  {
+    const char * ptr;
+    int glibcmajor = 0;
+
+    if (gnu_get_libc_version != 0)
+    {
+      ptr = gnu_get_libc_version ();
+      glibcmajor = 4;
+    }
+    else if (&__libc_version != 0)
+    {
+      ptr = __libc_version;
+      glibcmajor = 4;
+    }
+    else
+      ptr = __linux_C_lib_version;
+
+    while (!isdigit (*ptr))
+      ptr++;
+
+    sscanf (ptr, "%d.%d.%d", &libcmajor, &libcminor, &libcteeny);
+    libcmajor += glibcmajor;
+  }
+  if ((libcmajor == 5) && (!(libcminor == 99))) // see xc/config/cf/linux.cf in the XFree86 distribution
+    return 0;
+  else
+    return 1;
+}
+  
+    ],
+    AC_MSG_RESULT(yes)
+echo "***"
+echo "*** X11 compilation has been enabled and libc5 was found."
+echo "*** This means it is likely that your libX11 was built with"
+echo "*** libc5 and the X11 defaults for libc5 on linux."
+echo "***"
+echo "*** There may be unexplained XIO errors causing FreeAmp not to"
+echo "*** work.  See http://www.freeamp.org/x11.html for details."
+echo "***"
+    ,
+    AC_MSG_RESULT(no),
+    AC_MSG_RESULT(assuming no)
+  )
+
+
+
+fi
+
+dnl ******************
+dnl Check for dynamic loading library
+dnl ******************
+AC_CHECK_LIB(dl, dlopen, foo="bar",
+  AC_MSG_ERROR([FreeAmp requires the ability to load libraries dynamically (-ldl must work)])
+)
+
 
 dnl Check for some more stuff
-
 
 AC_SUBST(target_os)
 
@@ -152,7 +273,6 @@ AC_ARG_ENABLE(cmdline,
 	      esac])
 AM_CONDITIONAL(AM_ENABLE_CMDLINE, test "$cmdline" = "true")
 
-x11="true"
 
 AC_ARG_ENABLE(x11,
 		[  --enable-x11   Build the FreeAmp X11 GUI],
