minimally functioning freeamp gui. The procedures to build and add resources are, to say the least, very crude. Right now, one must manually run ui/freeamp/beos/res/BuildResource to create the resource file before make.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2533,8 +2533,7 @@ isunix="true"
 OSLINK=""
 FPIC="-fpic"
 LINKMOD="gcc -shared"
-FREEAMPLIBS='-ldl -lpthread $(X_LIBS) $(X_EXTRA_LIBS) $(EXTRALIBS)'
-SCPMOLIBS=""
+OSTYPE="UNIX";
 
 case "$host_os" in
   windowsnt)
@@ -2543,16 +2542,16 @@ case "$host_os" in
     ;;
   win32)
     isunix="false"
+    OSTYPE="CYGWIN"
     ;;
   beos*)
     cat >> confdefs.h <<\EOF
 #define HAVE_BEOS 1
 EOF
 
+    OSTYPE="BEOS"
     CFLAGS="$CFLAGS -Wno-multichar -Wno-ctor-dtor-privacy"
     LINKMOD='g++ -nostart -Xlinker -soname=${@F} freeamp'
-    FREEAMPLIBS="-lbe -lroot"
-    SCPMOLIBS="-lmedia -lbe -lroot"
     isunix="false"
     ;;
   linux*)
@@ -2569,7 +2568,7 @@ EOF
       LINKMOD="$CC -G"	
     fi
                     cat > conftest.$ac_ext <<EOF
-#line 2573 "configure"
+#line 2572 "configure"
 #include "confdefs.h"
 #include <pthread.h>
 #ifdef PTHREAD_MUTEX_ERRORCHECK
@@ -2596,6 +2595,7 @@ rm -f conftest*
     
 esac  
 
+
 cat >> confdefs.h <<EOF
 #define HOST_OS "${host_os}"
 EOF
@@ -2610,11 +2610,9 @@ OSINC="-Ibase/unix/include -Ibase/unix/$host_os/include -Iui/freeamp/unix/includ
 OSDEP="unix/$host_os"
 
 if test "$isunix" = "false"  ; then
-  OSINC="-Ibase/$host_os/include -Iui/freeamp/$host_os"
+  OSINC="-Ibase/$host_os/include -Iui/freeamp/$host_os/include"
   OSDEP="$host_os"
 fi
-
-
 
 
 
@@ -2658,17 +2656,17 @@ fi
 
 ac_safe=`echo "esd.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for esd.h""... $ac_c" 1>&6
-echo "configure:2662: checking for esd.h" >&5
+echo "configure:2660: checking for esd.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2667 "configure"
+#line 2665 "configure"
 #include "confdefs.h"
 #include <esd.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2672: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2670: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2695,7 +2693,7 @@ if test "$have_esound" = "true"; then
   # Extract the first word of "esd-config", so it can be a program name with args.
 set dummy esd-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2699: checking for $ac_word" >&5
+echo "configure:2697: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_ESD_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2773,9 +2771,9 @@ elif test "$host_os" = "beos"; then
 else
 
   echo $ac_n "checking for MIT PThreads""... $ac_c" 1>&6
-echo "configure:2777: checking for MIT PThreads" >&5
+echo "configure:2775: checking for MIT PThreads" >&5
   cat > conftest.$ac_ext <<EOF
-#line 2779 "configure"
+#line 2777 "configure"
 #include "confdefs.h"
 #include <pthread.h>
 EOF
@@ -2796,9 +2794,9 @@ rm -f conftest*
 
   
   echo $ac_n "checking for Base LinuxThreads""... $ac_c" 1>&6
-echo "configure:2800: checking for Base LinuxThreads" >&5
+echo "configure:2798: checking for Base LinuxThreads" >&5
   cat > conftest.$ac_ext <<EOF
-#line 2802 "configure"
+#line 2800 "configure"
 #include "confdefs.h"
 #include <pthread.h>
 EOF
@@ -2821,9 +2819,9 @@ rm -f conftest*
 
   
   echo $ac_n "checking for LinuxThreads w/ErrorCheck Mutex""... $ac_c" 1>&6
-echo "configure:2825: checking for LinuxThreads w/ErrorCheck Mutex" >&5
+echo "configure:2823: checking for LinuxThreads w/ErrorCheck Mutex" >&5
   cat > conftest.$ac_ext <<EOF
-#line 2827 "configure"
+#line 2825 "configure"
 #include "confdefs.h"
 #include <pthread.h>
 EOF
@@ -2847,13 +2845,13 @@ rm -f conftest*
   if test "$mitpth" = "false"; then
       if test "$ltr" = "false"; then
   	echo $ac_n "checking for broken Slackware MIT PThreads header (Obj C stub) and implementation""... $ac_c" 1>&6
-echo "configure:2851: checking for broken Slackware MIT PThreads header (Obj C stub) and implementation" >&5
+echo "configure:2849: checking for broken Slackware MIT PThreads header (Obj C stub) and implementation" >&5
   	if test "$cross_compiling" = yes; then
   echo "$ac_t""assuming no" 1>&6
   	
 else
   cat > conftest.$ac_ext <<EOF
-#line 2857 "configure"
+#line 2855 "configure"
 #include "confdefs.h"
 
   	    #define _MIT_POSIX_THREADS 1
@@ -2865,7 +2863,7 @@ else
               }
   	    
 EOF
-if { (eval echo configure:2869: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2867: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   cat >> confdefs.h <<\EOF
 #define HAVE_BROKENMITPTHREADS 1
@@ -2929,15 +2927,22 @@ fi
 #AM_CONDITIONAL(AM_ENABLE_X11, test "$x11" = "true")
 
 FAUIPLUGIN=plugins/freeamp-${host_os}.ui
-if test "$isunix" = "false" -o "$x11" = "false"; then
-  echo "configure: warning: not compiling freeamp-$host_os ui plugin" 1>&2
-else
+FREEAMPUITYPE="X11"
+if test "$host_os" = "beos"; then
+  FREEAMPUITYPE="BEOS"
   OSDEPPLUGINS="$OSDEPPLUGINS $FAUIPLUGIN";
-  EXTRALIBS="$EXTRALIBS -lXpm"
+else
+  if test "$isunix" = "false" -o "$x11" = "false"; then
+    echo "configure: warning: not compiling freeamp-$host_os ui plugin" 1>&2
+  else
+    OSDEPPLUGINS="$OSDEPPLUGINS $FAUIPLUGIN";
+    EXTRALIBS="$EXTRALIBS -lXpm"
+  fi
 fi
 
+
 echo $ac_n "checking for initscr in -lncurses""... $ac_c" 1>&6
-echo "configure:2941: checking for initscr in -lncurses" >&5
+echo "configure:2946: checking for initscr in -lncurses" >&5
 ac_lib_var=`echo ncurses'_'initscr | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2945,7 +2950,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lncurses  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2949 "configure"
+#line 2954 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2956,7 +2961,7 @@ int main() {
 initscr()
 ; return 0; }
 EOF
-if { (eval echo configure:2960: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2965: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2976,7 +2981,7 @@ else
   echo "$ac_t""no" 1>&6
 
 	echo $ac_n "checking for initscr in -lcurses""... $ac_c" 1>&6
-echo "configure:2980: checking for initscr in -lcurses" >&5
+echo "configure:2985: checking for initscr in -lcurses" >&5
 ac_lib_var=`echo curses'_'initscr | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2984,7 +2989,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lcurses  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2988 "configure"
+#line 2993 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2995,7 +3000,7 @@ int main() {
 initscr()
 ; return 0; }
 EOF
-if { (eval echo configure:2999: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3004: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3030,17 +3035,17 @@ fi
 	
 ac_safe=`echo "sys/asoundlib.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for sys/asoundlib.h""... $ac_c" 1>&6
-echo "configure:3034: checking for sys/asoundlib.h" >&5
+echo "configure:3039: checking for sys/asoundlib.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3039 "configure"
+#line 3044 "configure"
 #include "confdefs.h"
 #include <sys/asoundlib.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:3044: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:3049: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -3057,7 +3062,7 @@ fi
 if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   echo $ac_n "checking for main in -lasound""... $ac_c" 1>&6
-echo "configure:3061: checking for main in -lasound" >&5
+echo "configure:3066: checking for main in -lasound" >&5
 ac_lib_var=`echo asound'_'main | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3065,14 +3070,14 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lasound  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3069 "configure"
+#line 3074 "configure"
 #include "confdefs.h"
 
 int main() {
 main()
 ; return 0; }
 EOF
-if { (eval echo configure:3076: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3081: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3288,6 +3293,7 @@ s%@X_CFLAGS@%$X_CFLAGS%g
 s%@X_PRE_LIBS@%$X_PRE_LIBS%g
 s%@X_LIBS@%$X_LIBS%g
 s%@X_EXTRA_LIBS@%$X_EXTRA_LIBS%g
+s%@OSTYPE@%$OSTYPE%g
 s%@OSDEPOBJ@%$OSDEPOBJ%g
 s%@OSDEP@%$OSDEP%g
 s%@OSINC@%$OSINC%g
@@ -3295,10 +3301,9 @@ s%@OSLINK@%$OSLINK%g
 s%@FPIC@%$FPIC%g
 s%@LINKMOD@%$LINKMOD%g
 s%@build_cpu@%$build_cpu%g
-s%@FREEAMPLIBS@%$FREEAMPLIBS%g
-s%@SCPMOLIBS@%$SCPMOLIBS%g
 s%@ESD_CONFIG@%$ESD_CONFIG%g
 s%@ESD_LIBS@%$ESD_LIBS%g
+s%@FREEAMPUITYPE@%$FREEAMPUITYPE%g
 s%@CURSES@%$CURSES%g
 s%@EXTRALIBS@%$EXTRALIBS%g
 s%@OSDEPPLUGINS@%$OSDEPPLUGINS%g
