Lots of junk: Rename the freeamp.ui to freeamp-xlib.ui.. Seems better to me, since it won't be the default ui for much longer.  Fixed the alsa pmo to compile/work on the latest versions of alsa (>= 0.4.0).  Rename the MusicSearch class to MusicBrowser.  The Database class is no longer a template, too many problems.  Minor other unix related cleanups.
Initial import of the unix musicbrowser/playlist ui.  It's only partially
functional, but the rest should go fairly quickly, just need to add callbacks
and the like.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,7 +12,7 @@ ac_help=
 ac_default_prefix=/usr/local
 # Any additions from configure.in:
 ac_help="$ac_help
-  --enable-x11            Build the FreeAmp X11 GUI"
+  --enable-xlib           Build the FreeAmp Xlib GUI"
 ac_help="$ac_help
   --with-x                use the X Window System"
 ac_help="$ac_help
@@ -1660,21 +1660,21 @@ EOF
 fi
 
 
-x11="true"
+xlib="true"
 
-# Check whether --enable-x11 or --disable-x11 was given.
-if test "${enable_x11+set}" = set; then
-  enableval="$enable_x11"
+# Check whether --enable-xlib or --disable-xlib was given.
+if test "${enable_xlib+set}" = set; then
+  enableval="$enable_xlib"
   case "${enableval}" in
-	  yes) x11="true" ;;
-	  no) x11="false" ;;
-	  *) { echo "configure: error: bad value ${enableval} for --enable-x11" 1>&2; exit 1; } ;;
+	  yes) xlib="true" ;;
+	  no) xlib="false" ;;
+	  *) { echo "configure: error: bad value ${enableval} for --enable-xlib" 1>&2; exit 1; } ;;
 	esac
 fi
 
 
 
-if test "$x11"="true"; then
+if test "$xlib"="true"; then
   # If we find X, set shell vars x_includes and x_libraries to the
 # paths, otherwise set no_x=yes.
 # Uses ac_ vars as temps to allow command line to override cache and checks.
@@ -2511,8 +2511,8 @@ fi
 
 
   if test "x$no_x" = "xyes"; then 
-     x11="false"
-     echo X11 not found. X11 UI build disabled.
+     xlib="false"
+     echo Xlib not found. Xlib UI build disabled.
   else
 
     CFLAGS="$CFLAGS $X_CFLAGS"
@@ -2553,16 +2553,16 @@ LIBS="$ac_save_LIBS"
 fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
-  x11="true"
+  xlib="true"
 else
   echo "$ac_t""no" 1>&6
-x11="false"
-      echo X11 not found. X11 UI build disabled.
+xlib="false"
+      echo Xlib not found. Xlib UI build disabled.
     
 fi
 
 
-    if test "$x11" = "true"; then
+    if test "$xlib" = "true"; then
        echo $ac_n "checking for XShapeQueryExtension in -lXext""... $ac_c" 1>&6
 echo "configure:2568: checking for XShapeQueryExtension in -lXext" >&5
 ac_lib_var=`echo Xext'_'XShapeQueryExtension | sed 'y%./+-%__p_%'`
@@ -2598,18 +2598,18 @@ LIBS="$ac_save_LIBS"
 fi
 if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   echo "$ac_t""yes" 1>&6
-  x11="true"
+  xlib="true"
 else
   echo "$ac_t""no" 1>&6
-x11="false"
-         echo X11 Shape Extension not found.  X11 UI build disabled.
+xlib="false"
+         echo Xlib Shape Extension not found.  Xlib UI build disabled.
        
 fi
 
 
     fi
 
-    if test "$x11" = "true"; then
+    if test "$xlib" = "true"; then
        ac_safe=`echo "X11/xpm.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for X11/xpm.h""... $ac_c" 1>&6
 echo "configure:2616: checking for X11/xpm.h" >&5
@@ -2638,7 +2638,7 @@ rm -f conftest*
 fi
 if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   echo "$ac_t""yes" 1>&6
-  x11="true"
+  xlib="true"
 else
   echo "$ac_t""no" 1>&6
  echo "Hmmm. X11/xpm.h not showing up in your include path."
@@ -2649,8 +2649,8 @@ else
     echo "Found $x_includes/X11/xpm.h."
   fi
   if test $z = 0; then	
-         x11="false"
-         echo XPM Header not found. X11 UI build disabled.
+         xlib="false"
+         echo XPM Header not found. Xlib UI build disabled.
   fi
 
        
@@ -2989,6 +2989,128 @@ fi
 
 
 
+
+have_gtk="true"
+
+if test "$have_gtk" = "true"; then
+  # Extract the first word of "gtk-config", so it can be a program name with args.
+set dummy gtk-config; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:3000: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_GTK_CONFIG'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$GTK_CONFIG" in
+  /*)
+  ac_cv_path_GTK_CONFIG="$GTK_CONFIG" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_GTK_CONFIG="$GTK_CONFIG" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_GTK_CONFIG="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_GTK_CONFIG" && ac_cv_path_GTK_CONFIG="no"
+  ;;
+esac
+fi
+GTK_CONFIG="$ac_cv_path_GTK_CONFIG"
+if test -n "$GTK_CONFIG"; then
+  echo "$ac_t""$GTK_CONFIG" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+  if test "$GTK_CONFIG" = "no"; then
+     have_gtk="false"
+  else
+     GTK_CFLAGS=`$GTK_CONFIG --cflags`
+     GTK_LIBS=`$GTK_CONFIG --libs`
+     min_gtk_version="1.2.2"
+     echo $ac_n "checking for GTK+ version >= $min_gtk_version""... $ac_c" 1>&6
+echo "configure:3040: checking for GTK+ version >= $min_gtk_version" >&5
+     gtk_config_major=`$GTK_CONFIG --version | sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\1/'`
+     gtk_config_minor=`$GTK_CONFIG --version | sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\2/'`
+     gtk_config_micro=`$GTK_CONFIG --version | sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\3/'`
+     ac_save_CFLAGS="$CFLAGS"
+     ac_save_LIBS="$LIBS"
+     CFLAGS="$CFLAGS $GTK_CFLAGS"
+     LIBS="$GTK_LIBS $LIBS"
+
+     if test "$cross_compiling" = yes; then
+  have_gtk=false]
+else
+  cat > conftest.$ac_ext <<EOF
+#line 3053 "configure"
+#include "confdefs.h"
+
+#include <gtk/gtk.h>
+#include <stdio.h>
+#include <stdlib.h>
+
+int main()
+{
+  int major, minor, micro;
+  char *tmp_version;
+
+  tmp_version = g_strdup("$min_gtk_version");
+  sscanf(tmp_version, "%d.%d.%d", &major, &minor, &micro);
+  if ((gtk_major_version != $gtk_config_major) ||
+      (gtk_minor_version != $gtk_config_minor) ||
+      (gtk_micro_version != $gtk_config_micro))
+      exit(1);
+  if ((gtk_major_version > major) ||
+     ((gtk_major_version == major) && (gtk_minor_version > minor)) ||
+     ((gtk_major_version == major) && (gtk_minor_version == minor) && (gtk_micro_version >= micro)))
+     return 0;
+  printf("\n*** An old version of GTK+ (%d.%d.%d) was found.\n",
+         gtk_major_version, gtk_minor_version, gtk_micro_version);
+  return 1;
+}
+EOF
+if { (eval echo configure:3080: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  :
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  have_gtk=false
+fi
+rm -fr conftest*
+fi
+
+    CFLAGS="$ac_save_CFLAGS"
+    LIBS="$ac_save_LIBS" 
+    if test "$have_gtk" = "false"; then
+       echo "$ac_t""no" 1>&6
+    else
+       echo "$ac_t""yes" 1>&6
+    fi
+  fi
+fi
+
+if test "$have_gtk" = "true"; then
+  MUSICBROWSERPLUGIN=plugins/musicbrowser.ui
+  OSDEPPLUGINS="$OSDEPPLUGINS $MUSICBROWSERPLUGIN"
+  OSINC="$OSINC -Iui/musicbrowser/unix"
+  CFLAGS="$CFLAGS $GTK_CFLAGS"
+else
+  GTK_CFLAGS=""
+  GTK_LIBS=""
+fi
+
+
+
+
 # Check whether --enable-rio or --disable-rio was given.
 if test "${enable_rio+set}" = set; then
   enableval="$enable_rio"
@@ -3036,9 +3158,9 @@ elif test "$host_os" = "beos"; then
 else
 
   echo $ac_n "checking for MIT PThreads""... $ac_c" 1>&6
-echo "configure:3040: checking for MIT PThreads" >&5
+echo "configure:3162: checking for MIT PThreads" >&5
   cat > conftest.$ac_ext <<EOF
-#line 3042 "configure"
+#line 3164 "configure"
 #include "confdefs.h"
 #include <pthread.h>
 EOF
@@ -3059,9 +3181,9 @@ rm -f conftest*
 
   
   echo $ac_n "checking for Base LinuxThreads""... $ac_c" 1>&6
-echo "configure:3063: checking for Base LinuxThreads" >&5
+echo "configure:3185: checking for Base LinuxThreads" >&5
   cat > conftest.$ac_ext <<EOF
-#line 3065 "configure"
+#line 3187 "configure"
 #include "confdefs.h"
 #include <pthread.h>
 EOF
@@ -3084,9 +3206,9 @@ rm -f conftest*
 
   
   echo $ac_n "checking for LinuxThreads w/ErrorCheck Mutex""... $ac_c" 1>&6
-echo "configure:3088: checking for LinuxThreads w/ErrorCheck Mutex" >&5
+echo "configure:3210: checking for LinuxThreads w/ErrorCheck Mutex" >&5
   cat > conftest.$ac_ext <<EOF
-#line 3090 "configure"
+#line 3212 "configure"
 #include "confdefs.h"
 #include <pthread.h>
 EOF
@@ -3110,13 +3232,13 @@ rm -f conftest*
   if test "$mitpth" = "false"; then
       if test "$ltr" = "false"; then
   	echo $ac_n "checking for broken Slackware MIT PThreads header (Obj C stub) and implementation""... $ac_c" 1>&6
-echo "configure:3114: checking for broken Slackware MIT PThreads header (Obj C stub) and implementation" >&5
+echo "configure:3236: checking for broken Slackware MIT PThreads header (Obj C stub) and implementation" >&5
   	if test "$cross_compiling" = yes; then
   echo "$ac_t""assuming no" 1>&6
   	
 else
   cat > conftest.$ac_ext <<EOF
-#line 3120 "configure"
+#line 3242 "configure"
 #include "confdefs.h"
 
   	    #define _MIT_POSIX_THREADS 1
@@ -3128,7 +3250,7 @@ else
               }
   	    
 EOF
-if { (eval echo configure:3132: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:3254: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   cat >> confdefs.h <<\EOF
 #define HAVE_BROKENMITPTHREADS 1
@@ -3178,16 +3300,16 @@ fi
 #AM_CONDITIONAL(AM_ENABLE_CMDLINE, test "$cmdline" = "true")
 
 
-FAUIPLUGIN=plugins/freeamp.ui
-if test "$isunix" = "false" -o "$x11" = "false"; then
-  echo "configure: warning: not compiling freeamp.ui plugin" 1>&2
+FAUIPLUGIN=plugins/freeamp-xlib.ui
+if test "$isunix" = "false" -o "$xlib" = "false"; then
+  echo "configure: warning: not compiling freeamp-xlib.ui plugin" 1>&2
 else
   OSDEPPLUGINS="$OSDEPPLUGINS $FAUIPLUGIN";
   EXTRALIBS="$EXTRALIBS -lXpm"
 fi
 
 echo $ac_n "checking for initscr in -lncurses""... $ac_c" 1>&6
-echo "configure:3191: checking for initscr in -lncurses" >&5
+echo "configure:3313: checking for initscr in -lncurses" >&5
 ac_lib_var=`echo ncurses'_'initscr | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3195,7 +3317,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lncurses  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3199 "configure"
+#line 3321 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -3206,7 +3328,7 @@ int main() {
 initscr()
 ; return 0; }
 EOF
-if { (eval echo configure:3210: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3332: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3226,7 +3348,7 @@ else
   echo "$ac_t""no" 1>&6
 
 	echo $ac_n "checking for initscr in -lcurses""... $ac_c" 1>&6
-echo "configure:3230: checking for initscr in -lcurses" >&5
+echo "configure:3352: checking for initscr in -lcurses" >&5
 ac_lib_var=`echo curses'_'initscr | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3234,7 +3356,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lcurses  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3238 "configure"
+#line 3360 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -3245,7 +3367,7 @@ int main() {
 initscr()
 ; return 0; }
 EOF
-if { (eval echo configure:3249: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3371: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3280,17 +3402,17 @@ fi
 	
 ac_safe=`echo "sys/asoundlib.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for sys/asoundlib.h""... $ac_c" 1>&6
-echo "configure:3284: checking for sys/asoundlib.h" >&5
+echo "configure:3406: checking for sys/asoundlib.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3289 "configure"
+#line 3411 "configure"
 #include "confdefs.h"
 #include <sys/asoundlib.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:3294: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:3416: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -3307,7 +3429,7 @@ fi
 if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   echo "$ac_t""yes" 1>&6
   echo $ac_n "checking for main in -lasound""... $ac_c" 1>&6
-echo "configure:3311: checking for main in -lasound" >&5
+echo "configure:3433: checking for main in -lasound" >&5
 ac_lib_var=`echo asound'_'main | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3315,14 +3437,14 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lasound  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3319 "configure"
+#line 3441 "configure"
 #include "confdefs.h"
 
 int main() {
 main()
 ; return 0; }
 EOF
-if { (eval echo configure:3326: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3448: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3359,6 +3481,8 @@ if test "$have_alsa" = "true"; then
   OSINC="$OSINC -Iio/alsa/$OSDEP/include"
   echo "$ac_t""compiling alsa soundcard plugin" 1>&6
 fi
+
+
 
 
 
@@ -3548,6 +3672,9 @@ s%@LINKMOD@%$LINKMOD%g
 s%@build_cpu@%$build_cpu%g
 s%@ESD_CONFIG@%$ESD_CONFIG%g
 s%@ESD_LIBS@%$ESD_LIBS%g
+s%@GTK_CONFIG@%$GTK_CONFIG%g
+s%@GTK_CFLAGS@%$GTK_CFLAGS%g
+s%@GTK_LIBS@%$GTK_LIBS%g
 s%@CURSES@%$CURSES%g
 s%@EXTRALIBS@%$EXTRALIBS%g
 s%@OSDEPPLUGINS@%$OSDEPPLUGINS%g
