Added support for using sun cc in linking;
Added testefor PTHREAD_MUTEX_ERRORCHECK which doesn't exist on solaris less
than 2.7! Looks like I better hunt down the multiple locking problems after
all.

diff --git a/experimental/configure.in b/experimental/configure.in
--- a/experimental/configure.in
+++ b/experimental/configure.in
@@ -1,4 +1,4 @@
-dnl $Id: configure.in,v 1.9 1999/04/27 21:03:22 mhw Exp $
+dnl $Id: configure.in,v 1.10 1999/04/28 21:36:12 dogcow Exp $
 dnl FreeAmp - The Free MP3 Player
 dnl Portions copyright (C) 1998 GoodNoise
 dnl
@@ -177,6 +177,7 @@ cmdline="true"
 isunix="true"
 OSLINK=""
 FPIC="-fpic"
+LINKMOD="gcc -shared"
 
 case "$host_os" in
   windowsnt)
@@ -198,9 +199,24 @@ dnl not needed.
   solaris*)
     host_os="solaris"
     if test "$GCC" != "yes" ; then
-dnl probably Sun CC.
+      dnl probably Sun CC.
       FPIC="-Kpic"
-    fi	
+      LINKMOD="$CC -G"	
+    fi
+    dnl thank you, oh autoconf, for the oh-so-accurately named
+    dnl AC_EGREP_HEADER, which only uses egrep after it PUTS THE
+    dnl THING THROUGH CPP, MAKING #defineS NOT SHOW UP!
+    dnl This is why we use AC_EGREP_CPP instead.
+    AC_EGREP_CPP(yes,
+[#include <pthread.h>
+#ifdef PTHREAD_MUTEX_ERRORCHECK
+   yes
+#endif
+],
+      CFLAGS="$CFLAGS -DSOLDEBUGMUTEX"
+        AC_MSG_RESULT("Using Solaris debugging mutexen"),
+      AC_MSG_RESULT("Not using Solaris debugging mutexen")
+    )
     ;;
   *)
     echo "what are you?"
@@ -236,8 +252,9 @@ AC_SUBST(OSDEP)
 AC_SUBST(OSINC)
 AC_SUBST(OSLINK)
 AC_SUBST(FPIC)
-
+AC_SUBST(LINKMOD)
 AC_SUBST(build_cpu)
+AC_SUBST(CFLAGS)
 
 gtk="false"
 
@@ -291,62 +308,60 @@ elif test "$host_os" = "beos"; then
   AC_MSG_RESULT([This is BeOS; using BeOS threads.])
 else
 
-AC_MSG_CHECKING(for MIT PThreads)
-AC_EGREP_HEADER(PTHREAD_MUTEXTYPE_FAST,
-pthread.h,AC_DEFINE(HAVE_MITPTHREADS) AC_MSG_RESULT(yes)
-mitpth="true", 
-AC_MSG_RESULT(no)
-)
+  AC_MSG_CHECKING(for MIT PThreads)
+  AC_EGREP_HEADER(PTHREAD_MUTEXTYPE_FAST,
+  pthread.h,AC_DEFINE(HAVE_MITPTHREADS) AC_MSG_RESULT(yes)
+  mitpth="true", 
+  AC_MSG_RESULT(no)
+  )
+  
+  AC_MSG_CHECKING(for Base LinuxThreads)
+  AC_EGREP_HEADER(PTHREAD_MUTEX_FAST_NP,pthread.h, AC_DEFINE(HAVE_BASELINUXTHREADS) 
+  hblt="true"
+  ltr="true"
+  AC_MSG_RESULT(yes), 
+  AC_MSG_RESULT(no)
+  )
+  
+  AC_MSG_CHECKING(for LinuxThreads w/ErrorCheck Mutex)
+  AC_EGREP_HEADER(PTHREAD_MUTEX_ERRORCHECK_NP,pthread.h,AC_DEFINE(HAVE_ENHLINUXTHREADS)
+  ltr="true"
+  AC_MSG_RESULT(yes), 
+  AC_MSG_RESULT(no)
+  )
+  
+  if test "$mitpth" = "false"; then
+      if test "$ltr" = "false"; then
+  	AC_MSG_CHECKING(for broken Slackware MIT PThreads header (Obj C stub) and implementation)
+  	AC_TRY_RUN([
+  	    #define _MIT_POSIX_THREADS 1
+  	    #include <pthread.h>
+  	    int main(int argc,char**argv) {
+  		int foo;
+                  foo = 5 + PTHREAD_MUTEXTYPE_DEBUG;
+  		return 0;
+              }
+  	    ],
+  	    AC_DEFINE(HAVE_BROKENMITPTHREADS)
+  	    AC_DEFINE(HAVE_MITPTHREADS)
+  	    mitpth="true"
+  	    AC_MSG_RESULT(yes),
+  	    AC_MSG_RESULT(no),
+  	    AC_MSG_RESULT(assuming no)
+  	)
+      fi
+  fi
+  
+  
+  if test "$mitpth" = "false"; then
+     if test "$ltr" = "false"; then
+        echo "Can't find MIT PThreads or LinuxThreads complete development headers in /usr/include or /usr/local/include"
+        echo "Configure will stop."
+        exit 1
+     fi 
+  fi
 
-AC_MSG_CHECKING(for Base LinuxThreads)
-AC_EGREP_HEADER(PTHREAD_MUTEX_FAST_NP,pthread.h, AC_DEFINE(HAVE_BASELINUXTHREADS) 
-hblt="true"
-ltr="true"
-AC_MSG_RESULT(yes), 
-AC_MSG_RESULT(no)
-)
-
-AC_MSG_CHECKING(for LinuxThreads w/ErrorCheck Mutex)
-AC_EGREP_HEADER(PTHREAD_MUTEX_ERRORCHECK_NP,pthread.h,AC_DEFINE(HAVE_ENHLINUXTHREADS)
-ltr="true"
-AC_MSG_RESULT(yes), 
-AC_MSG_RESULT(no)
-)
-
-mitpth="true";
-
-if test "$mitpth" = "false"; then
-    if test "$ltr" = "false"; then
-	AC_MSG_CHECKING(for broken Slackware MIT PThreads header (Obj C stub) and implementation)
-	AC_TRY_RUN([
-	    #define _MIT_POSIX_THREADS 1
-	    #include <pthread.h>
-	    int main(int argc,char**argv) {
-		int foo;
-                foo = 5 + PTHREAD_MUTEXTYPE_DEBUG;
-		return 0;
-            }
-	    ],
-	    AC_DEFINE(HAVE_BROKENMITPTHREADS)
-	    AC_DEFINE(HAVE_MITPTHREADS)
-	    mitpth="true"
-	    AC_MSG_RESULT(yes),
-	    AC_MSG_RESULT(no),
-	    AC_MSG_RESULT(assuming no)
-	)
-    fi
-fi
-
-
-if test "$mitpth" = "false"; then
-   if test "$ltr" = "false"; then
-      echo "Can't find MIT PThreads or LinuxThreads complete development headers in /usr/include or /usr/local/include"
-      echo "Configure will stop."
-      exit 1
-   fi 
-fi
-
-fi dnl solaris, linux, or what have you
+fi dnl solaris, linux, or what have you. I should really indent those.
 
 dnl *****
 
